### ISSUE TITLE
运行 pthon demo.py 失败

### ISSUE THREAD

**Issue by fbigun** [miaoerduo/cartoon-cat#1]

**Comment by yarving** [comment]
@fbigun 你的错误信息呢？
我试了下：
```
─[0] python demo.py
Traceback (most recent call last):
  File "demo.py", line 15, in <module>
    driver='path/to/phantomjs'                  # 驱动程序路径，firefox不需要
  File "/private/tmp/cartoon-cat/cartoon_cat/cartoon_cat.py", line 35, in __init__
    os.mkdir(self.__save_folder)
OSError: [Errno 2] No such file or directory: '/path/to/download'
Exception AttributeError: "CartoonCat instance has no attribute '_CartoonCat__browser'" in <bound method CartoonCat.__del__ of <cartoon_cat.cartoon_cat.CartoonCat instance at 0x1106e8908>> ignored
```
直接运行是运行不起来的，需要你修改这样代码：
https://github.com/miaoerduo/cartoon-cat/blob/master/demo.py#L13

**Comment by fbigun** [comment]
![_20170315193509](https://cloud.githubusercontent.com/assets/4226523/23946752/9a45e064-09b6-11e7-9659-0aea2f178dc2.png)

**Comment by fbigun** [comment]
Python 3.6.0 :: Continuum Analytics, Inc.

**Comment by fbigun** [comment]
@yarving  你的是python2 吗

**Comment by yarving** [comment]
@fbigun You still hasn't post your error message.

**Comment by fbigun** [comment]
我用python3解决了

这个是我的fork版本 https://github.com/fbigun/cartoon-cat.git
